name: Check Github seats

on:
  pull_request:
    branches:
      - master

jobs:

  check-available-seats:
    runs-on: ubuntu-latest

    steps:
      - name: Get available seats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -o data.json -H "authorization: token ${GITHUB_TOKEN}" https://api.github.com/orgs/onrunning
          cat data.json
          jq -r '.plan' data.json
          seats=$(jq -r '.plan.seats' data.json)
          filled_seats=$(jq -r '.plan.filled_seats' data.json)
          if [ ${seats} -gt ${filled_seats} ]; then
            echo "::error title=ERROR::There aren't enough seats available"
            exit 1
          fi

